#!/bin/sh
#
# Author: Jose Luis Rivas <joseluis at rivco.net>
# Filename: pp-clean
# Date: October 3, 2009, 16:01.
#

#
# Copyright (c) 2009 Jose Luis Rivas <joseluis at rivco.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

help="
This is a dumb script for cleaning up build dir from my conf of pkg-perl.
Run it without args and cleans ~/dev/debian/perl/builds/.

Options:
-v		Print version.
-h		Print this help.

Last version downloadable from:
http://scm.rivco.net/p/perl-packaging-tools/
"

version="
Downloader for debian-perl packages
Version: 0.01
Copyright 2009 Jose Luis Rivas <joseluis at rivco.net>
"

while test -n "$1"; do
	case $1 in
	-v|--version)
		echo "$version"; exit 0;;
	-h|--help)
		echo "$help"; exit 0;;
	*)
		echo "$help"; exit 0;;
	esac
done

if test -z $1; then
	echo "Cleaning build dir"
	rm ~/dev/debian/perl/builds/*
	echo "Clean :-)"
	exit 0
fi
